### ISSUE TITLE
I CANNOT INSERT MY Data to the database

### ISSUE THREAD

**Issue by raymord21** [jzniu/inft233#1]
THIS IS ALL MY CODE RIGHT HERE. FOR SOME REASON WHEN I RUN MY PAGE. IT GIVES ME THE FOLLOWING ERROR MESSAGE:

Error: INSERT INTO CUSTOMER (firstname, lastname, email, Custpassword)values ("raymord","nova","","master22");
Duplicate entry '0' for key 'PRIMARY'

I'm just implementing random data in my forms and trying to archive them in my database. 

<head>
    <title>Confirmation Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Bookason</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="http://www.inft.me/~reymord/index.php">Home</a></li>
                <li><a href="about.php">About us</a></li>
                <li><a href="products.php">Products</a></li> 
                <li><a href="checkout.php">Checkout</a></li> 
            </ul>
        </div>
    </nav>

    <?php
    $servername = "localhost";
    $username = "reymord";
    $password = "dtycts16";
    $dbname = "reymord";

// Create connection
    $conn = mysqli_connect($servername, $username, $password, $dbname);
// Check connection
    if (!$conn) {
        die("Connection failed: " . mysqli_connect_error());
    }

    // Escape user inputs for security
    $firstname =$_POST['firstname'];
    $lastname = $_POST['lastname'];
    $email = $_POST['email'];
    $Custpassword = $_POST['Custpassword'];

    $sql = "INSERT INTO CUSTOMER (firstname, lastname, email, Custpassword)"
    . 'values (' . "\"$firstname\"" . ',' . "\"$lastname\"" . ','. "\"$email\"" . ','. "\"$Custpassword\");";

    if (mysqli_query($conn, $sql)) {
        echo "New record created successfully";
    } else {
        echo "Error: " . $sql . "<br>" . mysqli_error($conn);
    }

    mysqli_close($conn);
    ?>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>
</html>

**Comment by jzniu** [comment]
The problem is the primary key in your table. Either you need to specify 
when you create the table that the ID key is auto increment (see 
http://www.w3schools.com/sql/sql_autoincrement.asp) or delete the field 
and use email as primary key. Either way is fine.

**Comment by raymord21** [comment]
Perfect Thank you Professor Niu Actually it was this to be specific. 

To use the GUI:

Click the STRUCTURE tab to see the list of existing fields

To set a field as the PRIMARY FIELD, click the gold key -- it will turn silver.

To set a field (usually the same field) as auto-increment:
a. Click CHANGE for that field
b. Look to the far right and checkmark the **AI box**
c. Click SAVE button.

I'm pushing all the things that I've done right now. It's has been really challenging but I got my registration process to store data in my database, and also my sign in to recognize users and welcome them if they put the right information, and give them an error if they're not register yet or typed something wrong.

**Comment by jzniu** [comment]
That's good. Keep working on it and try to finish as much as possible.
