### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by Bennyramirez08** [jzniu/inft233#2]
join_us-validation.php- where do I place the email message code within php ?

**Comment by jzniu** [comment]
That should be after you have checked if the two passwords match, if the 
user already exists, and you have successfully inserted a new record into 
the table, e.g., the last step before you display a success message, 
saying "A verification email has been sent to you. Please verify by 
clicking the link in the email." If any previous step fails, an error 
message should be displayed and you do not proceed to the following steps.

Remember to check the pointers in the handout. Sending verification emails 
is covered in one of the pointers.

**Comment by Bennyramirez08** [comment]
You gave us two email php codes in the pointers. Which one do I use to send the verification link. I'm also having trouble, I don't know what page I need to put that code in. Either in join_us-validation.php or join_us-verification.php ? I ask because every time I create an account the email does not get sent. 

Also, do I have to hash the password before I begin the email process ?

**Comment by Bennyramirez08** [comment]
Thank you for the help.

**Comment by jzniu** [comment]
The validation page should include all the steps I enumerated earlier. The 
verification page is the actual link that a new user clicks in the 
verification email and this page would mark that user verified in your 
database (i.e., you have a field noting whether the user is verified or 
not). I would suggest you to think about how a regular website handles 
registration and review the DFD processes we discussed a while ago. These 
steps are based on our thoughts then.

To send an email via your gmail account, follow this pointer: 
http://jeff.robbins.ws/code/pear-mail_gmail

The other pointer 
(http://code.tutsplus.com/tutorials/how-to-implement-email-verification-for-new-members--net-3824) 
is rather complete description of the whole process from user registration 
to verification to login authentication, e.g., all that you need to 
implement besides checkout, etc. But they use the traditional mail 
function in Step 5. You should use the gmail way described in the pointer 
above instead. The mail() function is not configured and not supported on 
inft.me.

You can hash using md5() function for example. But for testing purposes, 
you may start with plain-text password in the database without hashing. 
Once everything works fine, add md5 hashing.

**Comment by Bennyramirez08** [comment]
Every time I create a new account the email does not send. I put correct email addresses.

**Comment by jzniu** [comment]
If everything else is correct, try to log into your gmail account to see 
if there is any security warning. Sometimes Google detected that someone 
was trying to log into your gmail from a unknown location (inft.me in this 
case) and would block it. You need to respond to the security warning and 
confirm it's okay.

**Comment by Bennyramirez08** [comment]
I got it , it works now. Thank You

**Comment by Bennyramirez08** [comment]
Do we have to create a new database hash ?

**Comment by jzniu** [comment]
If everything else is working, adding hashing to passwords may be a 
1-minute work, if that's what you meant.

**Comment by Bennyramirez08** [comment]
Emails work now. To verify my account, am i supposed to do the hashing code ?

**Comment by jzniu** [comment]
Yes, that's another place you need hashing, which is explained in the last 
pointer.

**Comment by Bennyramirez08** [comment]
Okay, Is creating  a hash database necessary or  is "benny" the only database needed ?

**Comment by jzniu** [comment]
You don't need a new database, not even a new table. You still use the 
Customer table. You may only need to add a new field.

**Comment by Bennyramirez08** [comment]
I implemented the hashing code from the last pointer. I don't understand what the hash variable means.

**Comment by jzniu** [comment]
Hash is used to make the verification step secure. If hash is not used, 
your verification link would look quite simple and a fake link may be 
generated easily by anyone who tries to attack the system.

**Comment by Bennyramirez08** [comment]
So do I leave that hash code by itself ?

**Comment by Bennyramirez08** [comment]
**This is my code** 


<?php

mysql_connect("localhost", "benny", "dtycts16") or die(mysql_error()); // Connect to database server(localhost) with username and password.
mysql_select_db("benny") or die(mysql_error()); // Select registration database.
             
if(isset($_GET['username']) && !empty($_GET['useername']) AND isset($_GET['passsword']) && !empty($_GET['password'])){
    // Verify data
    $email = mysql_escape_string($_GET['username']); // Set email variable
    $hash = mysql_escape_string($_GET['hash']); // Set hash variable
                 
    $search = mysql_query("SELECT username, hash, active FROM Customer WHERE email='".$username."' AND hash='".$hash."' AND active='0'") or die(mysql_error()); 
    $match  = mysql_num_rows($search);
                 
    if($match > 0){
        // We have a match, activate the account
        mysql_query("UPDATE users SET active='1' WHERE email='".$username."' AND hash='".$hash."' AND active='0'") or die(mysql_error());
        echo '<div class="statusmsg">Your account has been activated, you can now login</div>';
    }else{
        // No match -> invalid url or account has already been activated.
        echo '<div class="statusmsg">The url is either invalid or you already have activated your account.</div>';
    }
                 
}else{
    // Invalid approach
    echo '<div class="statusmsg">Invalid approach, please use the link that has been send to your email.</div>';
}
?>

**Comment by jzniu** [comment]
Later on when you have more time and if you want to, read the last chapter 
from the book. I think they explain more on this. You would need to 
understand why and how it works to make it work.
