### ISSUE TITLE
I'm having this problem when verifying account through email.

### ISSUE THREAD

**Issue by raymord21** [jzniu/inft233#3]
Access denied for user 'apache'@'localhost' (using password: NO) 
For some reason this the only part I'm missing so far.

**Comment by jzniu** [comment]
Where in your code were you trying to use 'apache'? If you are accessing 
the database, you should use your own username.

**Comment by raymord21** [comment]
I'm not using Apache no where, all I'm using for my username is reymord, and for the servername localhost. for some reason I'm getting that error, i don't know where it's coming from. 

Another Question. Do we have to design the page entirely? or the main part about this projects is just creating the registration/sign in parts, and processes.

**Comment by raymord21** [comment]
HERE IS MY CODE !
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="styles.css">
        <title>Registration Page</title>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Bookason</a>
                </div>
                <ul class="nav navbar-nav">
                    <li class="active"><a href="http://www.inft.me/~reymord/index.php">Home</a></li>
                    <li><a href="#">About us</a></li>
                    <li><a href="http://www.inft.me/~reymord/signin.php">Sign In</a></li> 
                    <li><a href="http://www.inft.me/~reymord/registration.php">Register</a></li> 
                </ul>
            </div>
        </nav>
        <?php
        $servername = "localhost";
        $username = "reymord";
        $password = "dtycts16";
        $dbname = "reymord";


// Create connection
        $conn = mysqli_connect($servername, $username, $password, $dbname);
// Check connection
        if (!$conn) {
            die("Connection failed: " . mysqli_connect_error());
        }

        if (isset($_GET['email']) && !empty($_GET['email']) AND isset($_GET['hash']) && !empty($_GET['hash'])) {
            // Verify data
            $email = mysql_escape_string($_GET['email']); // Set email variable
            $hash = mysql_escape_string($_GET['hash']); // Set hash variable

            $search = mysql_query("SELECT email, hash, active FROM CUSTOMER WHERE email='" . $email . "' AND hash='" . $hash . "' AND active='0'") or die(mysql_error());
            $match = mysql_num_rows($search);

            if ($match > 0) {
                // We have a match, activate the account
                mysql_query("UPDATE CUSTOMER SET active='1' WHERE email='" . $email . "' AND hash='" . $hash . "' AND active='0'") or die(mysql_error());
                echo '<div class="statusmsg">Your account has been activated, you can now login</div>';
            } else {
                // No match -> invalid url or account has already been activated.
                echo '<div class="statusmsg">The url is either invalid or you already have activated your account.</div>';
            }
        } else {
            // Invalid approach
            echo '<div class="statusmsg">Invalid approach, please use the link that has been send to your email.</div>';
        }
        ?>
    </body>
</html>

**Comment by jzniu** [comment]
Then you saw that error message? on a web page you created?

Regarding the project, we don't need to worry about appearance, but focus 
on functionalities. Registration/login are just the first part, the first 
or two major processes in DFD. Checkout, billing and shipping are bit more 
complicated. But for now, I would say focus on the registration/login 
part. You won't have time to do the rest.

**Comment by jzniu** [comment]
Send me a verification link and let me try.

**Comment by raymord21** [comment]
I only see the error message when I try to access it without the link. 
I just sent you the link, to you Guttman email.  check your spam email. For some reason it send it directly there.

**Comment by jzniu** [comment]
You forgot to specify $conn in your invocations of mysql_query() besides 
the sql statement. Otherwise mysql would assume that you are trying to use 
a connection with no parameters specified, which would make apache, the 
webserver, the presumed user for the database. But apache doesn't have access.

**Comment by raymord21** [comment]
So you mean putting $conn instead of $search? in both of them?
$search = mysql_query("SELECT email, hash, active FROM CUSTOMER WHERE email='" . $email . "' AND hash='" . $hash . "' AND active='0'") or die(mysql_error());

**Comment by jzniu** [comment]
Try to use things like mysqli_query($conn, $sql) rather than 
mysql_query(). The latter is an old version and may not work. You may also 
have mixed the two different usages, leading to problems. Try to mysqli_* 
methods and you can use the few book chapters as references. Some pointers 
may have used the old version.

**Comment by jzniu** [comment]
Both. See my previous email.
